# Conditional Probability & Bayes Coding

In [1]:
# importing libraries
import numpy as np
import pandas as pd

In [2]:
# creating dataset
data = {
    "Gender": [
        "Female", "Female", "Female", "Female", "Female",
        "Male", "Male", "Male", "Male", "Male"
    ],
    "Passed": [
        "Yes", "Yes", "Yes", "No", "No",
        "Yes", "Yes", "No", "No", "No"
    ]
}

df = pd.DataFrame(data)

df

   Gender Passed
0  Female    Yes
1  Female    Yes
2  Female    Yes
3  Female     No
4  Female     No
5    Male    Yes
6    Male    Yes
7    Male     No
8    Male     No
9    Male     No

### Marginal Probability

In [3]:
p_female=(df['Gender']=='Female').mean()
p_female

np.float64(0.5)

In [4]:
p_female_and_passed=(
    (df['Gender']=='Female')&
    (df['Passed']=='Yes')
).mean()
p_female_and_passed

np.float64(0.3)

In [12]:
pd.crosstab(df['Gender'],df['Passed'],normalize=True)

Passed   No  Yes
Gender
Female  0.2  0.3
Male    0.3  0.2

### Conditional Probability

In [5]:
female_students = df[df["Gender"] == "Female"]

female_students

   Gender Passed
0  Female    Yes
1  Female    Yes
2  Female    Yes
3  Female     No
4  Female     No

In [6]:
# using its formula
p_female_and_passed = (
    (df["Gender"] == "Female") &
    (df["Passed"] == "Yes")
).mean()

p_female = (
    df["Gender"] == "Female"
).mean()

p_passed_given_female = p_female_and_passed / p_female

p_passed_given_female

np.float64(0.6)

In [13]:
pd.crosstab(
    df['Gender'],
    df['Passed'],
    normalize='index'
)

Passed   No  Yes
Gender
Female  0.4  0.6
Male    0.6  0.4

### Contingency Table

In [7]:
pd.crosstab(
    df["Gender"],
    df["Passed"]
)

Passed  No  Yes
Gender
Female   2    3
Male     3    2

In [14]:
pd.crosstab(df['Gender'],df['Passed'])

Passed  No  Yes
Gender
Female   2    3
Male     3    2

### Bayes Theorem

In [8]:
def bayes_theorem(p_a, p_b_given_a, p_b_given_not_a):

    p_b = (
        p_b_given_a * p_a
        +
        p_b_given_not_a * (1 - p_a)
    )

    p_a_given_b = (
        p_b_given_a * p_a
    ) / p_b

    return p_a_given_b

In [9]:
result = bayes_theorem(
    p_a=0.01,
    p_b_given_a=0.90,
    p_b_given_not_a=0.05
)

result

0.15384615384615385